### ISSUE TITLE
Fetching data

### ISSUE THREAD

**Issue by lexeech** [glopezep/react-ssr#1]
Hello, i wanna use your solution for my projects, but i cant understand how i can render data on page with SSR? _Can you explain how ?_

**Comment by glopezep** [comment]
Well, what you should do is the following:

`
import path from 'path'
import http from 'http'
import express from 'express'
import chalk from 'chalk'
import React from 'react'
import ReactDOMServer from 'react-dom/server'
import { StaticRouter } from 'react-router-dom'
import Page from './pages'
import Layout from './pages/components/Layout'
import request from 'request-promise-native' // you can use any other http request library

const context = {}
const app = express()
const server = http.createServer(app)
const port = process.env.PORT || 3000

const options = { 
  method: 'GET',
  uri: 'http://api.some-api.com/users',
  json: true
}

const users = await request(options)

const initialData = {
  users
};

app.use('/static', express.static(path.join('./dist')))
app.use((req, res) => {
  ReactDOMServer.renderToNodeStream(
    <StaticRouter
      location={req.url}
      context={context}
    >
      <Layout initialData={JSON.stringify(initialData)}>
        <Page {...initialData} />
      </Layout>
    </StaticRouter>
  ).pipe(res);
})

server.listen(port, () => {
  console.log(`${chalk.green('[react-ssr]')} server listening on port ${port}`)
})
`


all the data you will receive in the page component and at that moment you can pass that data to any of the views

**or you can request the data directly from the database with some orm**
